#!/usr/bin/env python3
"""
Injects status.js into the two consumers.

    src/index.html          ->  index.html
    src/hkpools-widget.js   ->  hkpools-widget.js

Each template carries a single marker line:

    // @@STATUS_ENGINE@@

which is replaced by status.js verbatim, fenced by the markers parity.js
looks for. The built files are committed so the widget can be pasted into
Scriptable and index.html opened without a build step — but they are
generated, so edit src/ and status.js, never the output.

    python build.py            build
    python build.py --check    exit 1 if the committed output is stale
"""
import argparse
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent
ENGINE = ROOT / "status.js"
MARKER = "// @@STATUS_ENGINE@@"
BANNER_MARKER = "@@BANNER@@"
OPEN_FENCE = "/* >>> injected from status.js — edit that file, not this one */"
CLOSE_FENCE = "/* <<< end status.js */"

TARGETS = [
    (ROOT / "src" / "index.html", ROOT / "index.html", "<!-- {} -->"),
    (ROOT / "src" / "hkpools-widget.js", ROOT / "hkpools-widget.js", "// {}"),
]

BANNER = ("GENERATED by build.py from src/{src} + status.js. "
          "Do not edit; your changes will be overwritten.")


def render(template: pathlib.Path, comment: str) -> str:
    text = template.read_text(encoding="utf-8")
    hits = [ln for ln in text.splitlines() if ln.strip() == MARKER]
    if len(hits) != 1:
        sys.exit(f"{template}: expected exactly one {MARKER} line, found {len(hits)}")

    engine = ENGINE.read_text(encoding="utf-8").rstrip("\n")
    # keep the marker's own indentation so the injected block sits in place
    indent = hits[0][: len(hits[0]) - len(hits[0].lstrip())]
    lines = [OPEN_FENCE, *engine.splitlines(), CLOSE_FENCE]
    block = "\n".join(indent + ln if ln.strip() else ln for ln in lines)

    body = text.replace(hits[0], block)

    # the banner sits where the template asks for it — in an HTML file that is
    # after the doctype, since a comment before it would mean quirks mode
    marks = [ln for ln in body.splitlines() if BANNER_MARKER in ln]
    if len(marks) != 1:
        sys.exit(f"{template}: expected exactly one {BANNER_MARKER} line, "
                 f"found {len(marks)}")
    return body.replace(marks[0], comment.format(BANNER.format(src=template.name)))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="verify the committed output matches, don't write")
    args = ap.parse_args()

    stale = []
    for template, out, comment in TARGETS:
        if not template.exists():
            sys.exit(f"missing template: {template}")
        built = render(template, comment)
        current = out.read_text(encoding="utf-8") if out.exists() else None
        if args.check:
            if current != built:
                stale.append(out.name)
            continue
        if current == built:
            print(f"  unchanged  {out.name}")
        else:
            out.write_text(built, encoding="utf-8")
            print(f"  wrote      {out.name}  ({len(built.splitlines())} lines)")

    if args.check:
        if stale:
            print("stale, re-run `python build.py`: " + ", ".join(stale),
                  file=sys.stderr)
            return 1
        print("built files are up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
