// Variables used by Scriptable.
// These must be at the very top of the file. Do not edit.
// icon-color: teal; icon-glyph: swimmer;
// GENERATED by build.py from src/hkpools-widget.js + status.js. Do not edit; your changes will be overwritten.
/* =====================================================================
   HK Pools — iOS home-screen widget (Scriptable)

   Small  : one pool, large.
   Medium : up to three, one line each, plus a weather row when it matters.

   DATA_URL below already points at this repo's published pools.json, so the
   script works as pasted — change it only if you forked or renamed the repo.
   Put the pool names in the widget's Parameter field, comma-separated.
   Partial names are fine: "kowloon park" finds "Kowloon Park Swimming Pool".

   The status logic lives in status.js and is injected below at build time —
   the web app runs the identical code, so the two can never disagree.
   ===================================================================== */

// Where the twice-daily scrape publishes. Forked the repo? Point this at your
// own copy: raw.githubusercontent.com/<you>/<repo>/main/pools.json
const DATA_URL =
  "https://raw.githubusercontent.com/iristkats/hkpools/main/pools.json";

const WARN_URL =
  "https://data.weather.gov.hk/weatherAPI/opendata/weather.php?dataType=warnsum&lang=en";

const CACHE = "hkpools-data.json";
const WARN_CACHE = "hkpools-warn.json";
const WARN_MAX_AGE_MIN = 30;      // beyond this a cached warning is ignored
const DEFAULT_POOLS = "Kowloon Park, Victoria Park, Morrison Hill";

// dot colours: all open / partly open / closed / group-training-only
const COLORS = {
  open: new Color("#34c759"),
  part: new Color("#ff9f0a"),
  shut: new Color("#ff453a"),
  priv: new Color("#bf5af0"),
  unk:  new Color("#8e8e93"),
};
const INK = new Color("#ffffff");
const DIM = new Color("#ffffff", 0.55);
const BG_TOP = new Color("#12232e");
const BG_BOTTOM = new Color("#0a141b");

/* >>> injected from status.js — edit that file, not this one */
/* =====================================================================
   HK Pools — status engine (canonical)

   The ONE implementation of "is this pool open right now". It is injected
   verbatim into both index.html and hkpools-widget.js at build time, so the
   web app and the iOS widget can never disagree.

   Pure functions only: no DOM, no network, no Scriptable APIs. Takes a pool
   object from pools.json plus a Date, returns status. Node can run it as-is,
   which is how the parity tests work.
   ===================================================================== */

function hkNow(){
  return new Date(new Date().toLocaleString("en-US",{timeZone:"Asia/Hong_Kong"}));
}
function mins(t){ const p=t.split(":"); return (+p[0])*60 + (+p[1]); }
function fmt(t){
  let p=t.split(":"), h=+p[0], m=p[1], ap=h<12?"am":"pm";
  h=h%12||12; return h+":"+m+ap;
}
function isoDay(d){
  return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")
         +"-"+String(d.getDate()).padStart(2,"0");
}
function inMonthRange(rng, mo, day){
  if(!rng) return false;
  var m1=rng[0][0], d1=rng[0][1], m2=rng[1][0], d2=rng[1][1];
  var a=m1*100+d1, b=m2*100+d2, x=mo*100+day;
  return a<=b ? (x>=a && x<=b) : (x>=a || x<=b);
}

/* ---- one day, one facility ----------------------------------------- */

/* The sessions a facility runs on a given date, before any clock is applied.
   Split out of facilityStatus so the same rules — maintenance, season,
   weekday, cleansing — can be asked about tomorrow, which is how the
   overnight "opens 6:30am" is worked out. */
function daySessions(p, f, d){
  var mo=d.getMonth()+1, day=d.getDate(), wd=(d.getDay()+6)%7;

  for(var i=0;i<p.maintenance.length;i++){
    var m=p.maintenance[i];
    if(inMonthRange(m.range,mo,day) &&
       (m.scope==="venue" || (m.targets && m.targets.indexOf(f.id)>=0)))
      return {blocked:"Maintenance", note:m.label, live:[]};
  }
  if(f.months && f.months.indexOf(mo)<0) return {blocked:"Out of season", live:[]};
  if(f.days && f.days.indexOf(wd)<0) return {blocked:"Not today", live:[]};

  var list, sdays;
  if(f.weekday_sessions && f.weekday_sessions.days.indexOf(wd)>=0){
    list=f.weekday_sessions.sessions; sdays=null;
  } else if(f.sessions){ list=f.sessions; sdays=f.session_days; }
  else { list=p.sessions; sdays=p.session_days; }
  if(!list || !list.length) return {blocked:"Unknown", live:[]};

  var sess=list.map(function(s,i){
    var dd = sdays && sdays[String(i)];
    return {from:s[0], to:s[1], skipped: dd ? dd.indexOf(wd)<0 : false};
  });

  // Weekly cleansing is a venue-wide clock blackout, never a session index:
  // facilities that open from the 2nd session have a different session list.
  var cleansing=false;
  if(p.cleansing_weekday===wd){
    var w = p.cleansing_window ||
            (p.sessions && p.sessions.length>1 ? ["10:00", p.sessions[1][1]] : null);
    if(w){
      var split=[];
      sess.forEach(function(s){
        if(s.skipped){ split.push(s); return; }
        if(mins(s.to)<=mins(w[0]) || mins(s.from)>=mins(w[1])){ split.push(s); return; }
        if(mins(s.from)<mins(w[0])) split.push({from:s.from,to:w[0],skipped:false});
        if(mins(s.to)>mins(w[1]))   split.push({from:w[1],to:s.to,skipped:false});
      });
      sess=split; cleansing=true;
    }
  }
  return {blocked:null, cleansing:cleansing,
          live:sess.filter(function(s){ return !s.skipped; })};
}

/* The temporary closure covering this facility at this moment, if any. */
function closureAt(p, f, dayISO, minute){
  return (p.closures||[]).filter(function(c){
    if(!c.targets || c.targets.indexOf(f.id)<0) return false;
    var s=c.start.slice(0,10), e=c.end?c.end.slice(0,10):"9999-12-31";
    if(!(s<=dayISO && dayISO<=e)) return false;
    var from = s===dayISO ? mins(c.start.slice(11)) : 0;
    var to   = (c.end && c.end.slice(0,10)===dayISO) ? mins(c.end.slice(11)) : 1440;
    return minute>=from && minute<to;
  })[0];
}

/* When today has no session left, the first one on a later day. Looks a week
   ahead and no further: past that a venue is in annual maintenance, and a
   date months out is not the useful thing to say. */
function nextOpening(p, f, now){
  for(var n=1;n<=7;n++){
    var d=new Date(now.getFullYear(), now.getMonth(), now.getDate()+n);
    var day=daySessions(p,f,d);
    if(day.blocked || !day.live.length) continue;
    var iso=isoDay(d);
    for(var i=0;i<day.live.length;i++){
      if(!closureAt(p,f,iso,mins(day.live[i].from)))
        return {at:day.live[i].from, days:n, wd:(d.getDay()+6)%7};
    }
  }
  return null;
}

/* ---- one facility -------------------------------------------------- */
function facilityStatus(p, f, now){
  var nowM=now.getHours()*60+now.getMinutes();
  var today=isoDay(now);
  var out={code:"shut", label:"Closed", note:f.note||"", reason:"", sessions:[]};

  if(!p.public || !f.public){
    out.code="priv"; out.label="Groups only";
    out.note=f.access_note||p.access_note||""; return out;
  }

  var d=daySessions(p,f,now);
  if(d.blocked==="Maintenance"){
    out.label="Maintenance"; out.note=d.note; out.reason=d.note; return out;
  }
  if(d.blocked==="Out of season"){ out.label="Out of season"; return out; }
  if(d.blocked==="Not today"){
    out.label="Not today"; out.reopen=nextOpening(p,f,now); return out;
  }
  if(d.blocked==="Unknown"){ out.code="unk"; out.label="Unknown"; return out; }

  if(d.cleansing) out.cleansing=true;
  var live=d.live;
  out.sessions=live;

  var closure=closureAt(p,f,today,nowM);
  if(closure){
    out.label="Closed";
    out.note=closure.reason + (closure.end ? "" : " (until further notice)");
    // `reason` marks a closure we can name; `note` may just be standing text
    // about the facility, which is never why it is shut right now.
    out.reason=out.note;
    return out;
  }

  var cur=live.filter(function(s){ return nowM>=mins(s.from) && nowM<mins(s.to); })[0];
  if(cur){
    out.code="open"; out.label="Open"; out.until=cur.to;
    // the session after this one, so the gap is visible before you set off
    live.forEach(function(s){
      if(mins(s.from)>=mins(cur.to) &&
         (!out.afterRaw || mins(s.from)<mins(out.afterRaw))) out.afterRaw=s.from;
    });
    // on the last session of the day the gap runs to tomorrow, and saying so
    // beats saying nothing: "until 10pm" alone reads as if more might follow
    if(!out.afterRaw) out.reopen=nextOpening(p,f,now);
    return out;
  }
  var next=live.filter(function(s){ return mins(s.from)>nowM; })[0];
  if(next){ out.code="soon"; out.label=fmt(next.from); out.nextRaw=next.from; return out; }

  // nothing left today — say when it is back rather than just "closed"
  out.reopen=nextOpening(p,f,now);
  return out;
}

/* ---- whole venue --------------------------------------------------- */
function venueStatus(p, now){
  var facs=p.facilities.map(function(f){ return {f:f, s:facilityStatus(p,f,now)}; });
  if(!p.public)
    return {code:"priv", label:"Groups only", facs:facs, openN:0, total:0, vague:[]};
  if(!facs.length)
    return {code:"unk", label:"Hours unknown", facs:facs, openN:0, total:0, vague:[]};

  var open=facs.filter(function(x){ return x.s.code==="open"; });
  var openN=open.length;
  var total=facs.filter(function(x){ return x.s.code!=="priv"; }).length;
  var lapOpen=open.some(function(x){ return x.f.lap; });

  // when open, the earliest closing time among open facilities
  var until=null;
  open.forEach(function(x){
    if(x.s.until && (!until || mins(x.s.until)<mins(until))) until=x.s.until;
  });
  // when open, when swimming resumes after that earliest close
  var resumeRaw=null;
  open.forEach(function(x){
    if(x.s.afterRaw && (!resumeRaw || mins(x.s.afterRaw)<mins(resumeRaw)))
      resumeRaw=x.s.afterRaw;
  });
  // when shut, the earliest next opening
  var nextRaw=null;
  facs.forEach(function(x){
    if(x.s.nextRaw && (!nextRaw || mins(x.s.nextRaw)<mins(nextRaw))) nextRaw=x.s.nextRaw;
  });

  var today=isoDay(now);
  var vague=(p.closures||[]).filter(function(c){
    return !c.targets && c.start.slice(0,10)<=today &&
           (c.end?c.end.slice(0,10):"9999-12-31")>=today;
  });

  var cleansing=facs.some(function(x){ return x.s.cleansing; });

  /* The soonest a facility is back on a later day. Shut for the rest of
     today, that is the whole answer; open on the last session of the day, it
     is what follows "next", standing in for a resume time there isn't one. */
  var back = openN===0 ? (nextRaw ? [] : facs)
                       : (resumeRaw ? [] : open);
  var reopen=null;
  back.forEach(function(x){
    var r=x.s.reopen;
    if(!r) return;
    if(!reopen || r.days<reopen.days ||
       (r.days===reopen.days && mins(r.at)<mins(reopen.at))) reopen=r;
  });

  var code, label;
  if(openN===0){
    code="shut";
    label = nextRaw ? "Opens "+fmt(nextRaw)
          : reopen ? "Opens "+fmt(reopen.at) : "Closed";
  }
  else if(vague.length){ code="part"; label="Open · see notice"; }
  else if(openN===total){ code="open"; label="All open"; }
  else { code="part"; label=openN+" of "+total+" open"; }

  return {code:code, label:label, facs:facs, openN:openN, total:total,
          lapOpen:lapOpen, until:until, resumeRaw:resumeRaw, nextRaw:nextRaw,
          reopen:reopen, vague:vague, cleansing:cleansing};
}

/* Node/test export; harmless in a browser or Scriptable. */
if (typeof module !== "undefined" && module.exports)
  module.exports = {hkNow, mins, fmt, isoDay, inMonthRange, daySessions,
                  closureAt, nextOpening, facilityStatus, venueStatus};
/* <<< end status.js */

/* ---- data ---------------------------------------------------------- */

const fm = FileManager.local();
const cachePath = (n) => fm.joinPath(fm.cacheDirectory(), n);

function readCache(name) {
  const p = cachePath(name);
  if (!fm.fileExists(p)) return null;
  try {
    return { data: JSON.parse(fm.readString(p)), at: fm.modificationDate(p) };
  } catch (e) {
    return null;
  }
}

function writeCache(name, obj) {
  try {
    fm.writeString(cachePath(name), JSON.stringify(obj));
  } catch (e) { /* a full disk must not take the widget down */ }
}

/* Returns {data, stale}. Falls back to the last good download offline, so a
   widget on the tube still shows correct session times — only closures age. */
async function loadData() {
  try {
    const req = new Request(DATA_URL);
    req.timeoutInterval = 15;
    const data = await req.loadJSON();
    if (!data || !Array.isArray(data.pools) || !data.pools.length)
      throw new Error("pools.json has no pools");
    writeCache(CACHE, data);
    return { data, stale: false };
  } catch (e) {
    const c = readCache(CACHE);
    if (c) return { data: c.data, stale: true };
    return { data: null, stale: true };
  }
}

/* Warnings that shut outdoor pools, per the LCSD rules in pools.json.
   Best-effort: a failed fetch just means no weather row. */
async function loadWarnings() {
  let raw = null;
  try {
    const req = new Request(WARN_URL);
    req.timeoutInterval = 8;
    raw = await req.loadJSON();
    writeCache(WARN_CACHE, raw);
  } catch (e) {
    const c = readCache(WARN_CACHE);
    const ageMin = c ? (Date.now() - c.at.getTime()) / 60000 : Infinity;
    if (!c || ageMin > WARN_MAX_AGE_MIN) return [];
    raw = c.data;
  }
  return relevantWarnings(raw);
}

function relevantWarnings(raw) {
  if (!raw || typeof raw !== "object") return [];
  const out = [];
  for (const key of Object.keys(raw)) {
    const w = raw[key];
    if (!w || w.actionCode === "CANCEL") continue;
    const code = String(w.code || "");
    // thunderstorm, any rainstorm signal, and typhoon signal 3 or above
    if (key === "WTS" || code.startsWith("WRAIN") ||
        (code.startsWith("TC") && !/TC1$/.test(code)))
      out.push(w.type || w.name || key);
  }
  return out;
}

/* ---- matching ------------------------------------------------------ */

/* Commas are what the setup notes tell you to use, but a phone keyboard
   offers plenty of other plausible separators — including the full-width
   punctuation a Chinese keyboard produces. No LCSD pool name or district
   contains any of these, so splitting on all of them is free. */
const SEPARATORS = /[,;/\n\t\u3001\uFF0C\uFF1B]+/;

/* Everything after a pipe is settings rather than pool names:
   "Kowloon Park, Victoria Park, Morrison Hill | one". */
const OPTION_MARK = /[|\uFF5C]/;

/* A colon narrows a venue to one of its pools: "victoria park: main" is the
   main pool alone, not the whole venue. Half a venue being open tells you
   little when it is the 50m lap pool you came for. */
const FACILITY_MARK = /[:\uFF1A]/;

/* Splits the Parameter into the pools and the settings after the pipe.
   `one` shows a single pool on the small tile however many are named, which is
   the roomiest it gets; `all` lists them, and is what happens by default. */
function readParam(param) {
  const parts = String(param || DEFAULT_POOLS).split(OPTION_MARK);
  const opts = (parts[1] || "").trim().toLowerCase();
  return {
    pools: parts[0],
    single: /\b(one|1|single|first)\b/.test(opts),
  };
}

/* "victoria park; mui wo: main" -> the pools they name, in the order given.
   Case-insensitive substring, so nobody has to type "Swimming Pool".
   `guessed` records anything only the typo pass could match — a substitution
   the reader never asked for is exactly what needs saying out loud. */
function pickPools(pools, param) {
  const wanted = (param || DEFAULT_POOLS)
    .split(SEPARATORS).map((s) => s.trim()).filter(Boolean);
  const picked = [], missing = [], guessed = [];

  for (const raw of wanted) {
    const parts = raw.split(FACILITY_MARK);
    const term = parts[0].trim().toLowerCase();
    const want = (parts[1] || "").trim().toLowerCase();
    if (!term) continue;

    const exact = pools.find((p) => p.name.toLowerCase().includes(term)) ||
                  pools.find((p) => (p.district || "").toLowerCase().includes(term));
    const p = exact || nearest(pools, term);
    if (!p) { missing.push(term); continue; }
    if (!exact) guessed.push(term + " → " + shortName(p.name));

    let f = null;
    if (want) {
      f = findFacility(p, want);
      if (!f) missing.push(want + " at " + shortName(p.name));
    }
    if (!picked.some((x) => x.p === p && x.f === f)) picked.push({ p: p, f: f });
  }
  return { picked, missing, guessed };
}

/* "main" -> the main pool; also matches the printed name and, so that a
   half-remembered word still lands, tolerates the same single typo. */
function findFacility(p, want) {
  const fs = p.facilities || [];
  return fs.find((f) => f.kind === want) ||
         fs.find((f) => f.name.toLowerCase().includes(want)) ||
         fs.find((f) => f.kind.startsWith(want)) ||
         fs.find((f) => f.name.toLowerCase().split(/\s+/)
                         .some((w) => editDistance(w, want) <= 1)) ||
         (want === "lap" ? fs.find((f) => f.lap) : null) || null;
}

/* One facility, shaped like a venue so the layouts need no special case. */
function facilityView(p, f, now) {
  const s = facilityStatus(p, f, now);
  const open = s.code === "open";
  return {
    code: open ? "open" : s.code === "priv" ? "priv"
        : s.code === "unk" ? "unk" : "shut",
    openN: open ? 1 : 0, total: 1, single: true,
    until: s.until || null, resumeRaw: s.afterRaw || null,
    nextRaw: s.nextRaw || null, reopen: s.reopen || null,
    cleansing: !!s.cleansing, vague: [], facs: [{ f: f, s: s }],
  };
}

function nearest(pools, term) {
  const words = term.split(/\s+/).filter(Boolean);
  if (!words.length) return null;

  // a word of one or two letters carries too little to spend a typo on, but
  // it still has to land — it is often the half that disambiguates ("mai wo")
  const matches = (h, w) =>
    w.length > 2 ? h.startsWith(w) || editDistance(h, w) <= 1 : h === w;

  let best = null, bestScore = 0, ties = 0;
  for (const p of pools) {
    const hay = (p.name + " " + (p.district || "")).toLowerCase().split(/\s+/);
    let score = 0;
    for (const w of words) if (hay.some((h) => matches(h, w))) score++;
    if (score > bestScore) { bestScore = score; best = p; ties = 1; }
    else if (score === bestScore && score > 0) ties++;
  }
  return bestScore === words.length && ties === 1 ? best : null;
}

/* Levenshtein, one row at a time — enough for one-character slips. */
function editDistance(a, b) {
  if (Math.abs(a.length - b.length) > 1) return 99;
  let prev = Array.from({ length: b.length + 1 }, (_, i) => i);
  for (let i = 1; i <= a.length; i++) {
    const row = [i];
    for (let j = 1; j <= b.length; j++)
      row[j] = Math.min(prev[j] + 1, row[j - 1] + 1,
                        prev[j - 1] + (a[i - 1] === b[j - 1] ? 0 : 1));
    prev = row;
  }
  return prev[b.length];
}

const hasOutdoor = (p) =>
  p.type !== "indoor" || (p.facilities || []).some((f) => f.location === "outdoor");

/* ---- phrasing ------------------------------------------------------ */

/* Times lose the ":00" so three of them fit on one widget line:
   "17:00" -> "5pm", "06:30" -> "6:30am". */
function compact(t) {
  return fmt(t).replace(":00", "");
}

/* The parts of a row's status line, most important first: when it shuts, when
   it is next open, and only then how much of the venue is available. Kept
   separate so a narrow tile can drop whole segments rather than cut through
   one and leave a dangling separator. */
function detailBits(st, tight) {
  if (st.code === "priv") return ["group training only"];
  if (st.code === "unk") return ["hours not published"];

  const bits = [];
  if (st.openN > 0) {
    bits.push("until " + compact(st.until));
    if (st.resumeRaw) bits.push("next " + compact(st.resumeRaw));
  } else {
    bits.push(st.nextRaw ? "Opens " + compact(st.nextRaw)
            : st.reopen ? "Opens " + reopenAt(st.reopen)
            : "closed today");
  }
  // the last session of the day: the gap runs to tomorrow morning
  const later = st.openN > 0 && !st.resumeRaw && st.reopen
              ? "next " + reopenAt(st.reopen) : "";
  const why = reason(st, tight);

  // Tomorrow is both the longest segment and the least urgent, so on a
  // cramped row it goes last and is dropped first: the pool count, which the
  // tile has no other way of saying, outlives it. Given room it reads better
  // beside the other clock time, before the count.
  if (later && !tight) bits.push(later);
  if (why) bits.push(why);
  if (later && tight) bits.push(later);
  return bits;
}

/* "until 5pm · next 6pm · all pools" */
function detailLine(st, tight) {
  return detailBits(st, tight).join(" · ");
}

/* The same, trimmed to `max` characters by dropping trailing segments — the
   pool count goes before the times do. */
function detailFor(st, tight, max) {
  const bits = detailBits(st, tight);
  while (bits.length > 1 && bits.join(" · ").length > max) bits.pop();
  return clip(bits.join(" · "), max);
}

/* The headline layout's two blocks: the muted lines saying what is true now,
   and the accent line saying when swimming next resumes. Kept apart because
   they are drawn in different colours; packed so neither wraps mid-segment.
   The small tile says "next 6:30am" where the medium has room for the word
   session — at 129 points wide, the label is what has to give, not the time. */
function stateLines(st, width, big) {
  if (st.code === "priv") return { info: ["group training only"], next: "" };
  if (st.code === "unk") return { info: ["hours not published"], next: "" };

  const bits = [];
  let next = "";
  if (st.openN > 0) {
    bits.push("until " + fmt(st.until));
    if (st.resumeRaw) next = fmt(st.resumeRaw);
    else if (st.reopen) next = WD[st.reopen.wd] + " " + fmt(st.reopen.at);
  } else {
    bits.push(st.nextRaw ? "Opens " + fmt(st.nextRaw)
            : st.reopen ? "Opens " + WD[st.reopen.wd] + " " + fmt(st.reopen.at)
            : "closed today");
  }
  const why = reason(st, false);
  if (why) bits.push(why);

  return {
    info: packLines(bits, width, 2),
    next: next ? clip((big ? "next session " : "next ") + next, width) : "",
  };
}

/* Why it looks the way it does — the half of the line that isn't a clock. */
function reason(st, tight) {
  if (st.openN > 0) {
    if (st.vague && st.vague.length) return tight ? "notice" : "see notice";
    if (st.single) return "";      // the name already says which pool
    if (st.openN === st.total) return tight ? "" : "all pools";
    return tight ? st.openN + "/" + st.total
                 : st.openN + " of " + st.total + " pools";
  }
  // cleansing explains a gap in today's timetable, not an empty evening —
  // past the last session it is no longer why the doors are shut
  if (st.cleansing && st.nextRaw) return "cleansing";

  const shut = st.facs.filter((x) => x.s.code !== "priv");
  if (!shut.length) return "";
  const all = (label) => shut.every((x) => x.s.label === label);
  if (all("Maintenance")) return tight ? "maintenance" : "annual maintenance";
  if (all("Out of season")) return tight ? "off season" : "out of season";

  // only a stated closure explains the shut — a facility's standing note is
  // not a reason, and outside opening hours nothing needs one
  const named = shut.filter((x) => x.s.reason);
  if (named.length !== shut.length) return "";
  return tight ? short(named[0].s.reason, 12) : short(named[0].s.reason, 22);
}

const short = (s, n) => (s.length > n ? s.slice(0, n - 1) + "…" : s);

const HEADLINE = { open: "OPEN", part: "PARTLY OPEN", shut: "CLOSED",
                   priv: "GROUPS ONLY", unk: "NO HOURS" };

const WD = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];

/* "Opens Sun 6:30am". The day is always named: at 11pm "opens 6:30am" reads
   like this morning, and a venue whose last session has passed can reopen at
   any hour of any later day. */
const reopenAt = (r) => WD[r.wd] + " " + compact(r.at);

/* Strip the boilerplate every LCSD venue name carries. */
const shortName = (n) => n.replace(/\s+Swimming Pool( Complex)?$/i, "");

/* "Morrison Hill" or, when one pool was singled out, "Morrison Hill · Main".
   The facility loses its own "pool" — every one of them is a pool. */
const facLabel = (f) => " · " + f.name.replace(/\s*pools?$/i, "");
const rowLabel = (r) => shortName(r.p.name) + (r.f ? facLabel(r.f) : "");

/* The same label cut to fit. The venue gives way, never the facility: a row
   reading "Morrison Hill · Main" that loses its tail becomes a claim about
   the whole venue, which is the one thing it is not. */
function fitLabel(r, max) {
  const venue = shortName(r.p.name);
  if (!r.f) return clip(venue, max);
  const fac = facLabel(r.f);
  return clip(venue, Math.max(6, max - fac.length)) + fac;
}

/* ---- fitting -------------------------------------------------------- */

/* Scriptable cannot measure text, and minimumScaleFactor shrinks each label
   independently — so a long venue name renders visibly smaller than a short
   one sitting right beneath it. Instead we size every row together: estimate
   widths from the character count, pick one size that suits the longest, and
   turn per-label shrinking off. Rows then differ in length, never in size.

   San Francisco averages a little over half its point size per character in
   mixed case; 0.53 is close enough to choose between half-point steps. */
const CHAR_W = 0.53;

/* Below these, a phone at arm's length stops being readable, so a label that
   will not fit is cut rather than shrunk further: "Sun Yat Sen Memor…" at a
   size you can read beats the whole name at one you cannot. Three pools at
   11pt still fit the small tile's height — the pressure is on width, and
   width is what truncation answers. */
const MIN_NAME = 11.5;
const MIN_DETAIL = 9.5;

/* Segments packed into at most `lines` lines of `width` characters. Each one
   is placed whole, so a line never breaks mid-segment and never ends on a
   dangling separator — which is what iOS would do left to its own wrapping.
   Segments that don't fit are dropped from the end, as detailBits orders them. */
function packLines(bits, width, lines) {
  const out = [];
  let cur = "";
  bits.forEach(function (b) {
    if (out.length >= lines) return;                  // nothing left to fill
    const join = cur ? cur + " · " + b : b;
    if (join.length <= width || !cur) { cur = join; return; }
    out.push(cur);
    cur = b;
  });
  if (cur && out.length < lines) out.push(cur);
  return out.map((l) => clip(l, width));
}

const detailRows = (st, tight, width, lines) =>
  packLines(detailBits(st, tight), width, lines);

/* Sizing and trimming argue in a circle: the size decides how much text fits,
   and the text decides the size. Settle it by fitting the whole line, dropping
   whatever that size cannot hold, then fitting again to what survived — so a
   segment that was never going to be drawn can't shrink the row it was cut
   from. One extra pass is enough: dropping text only ever raises the size,
   and a raised size never drops more. */
function fitDetails(rows, tight, width, lines, max, min) {
  const at = (size) =>
    rows.map((r) => detailRows(r.st, tight, budget(width, size), lines));
  // the whole line has every line's width to spread over; each one, only its own
  const longest = (ls) =>
    ls.map((l) => l.reduce((a, b) => (a.length > b.length ? a : b), ""));
  const first = fitSize(rows.map((r) => detailLine(r.st, tight)),
                        width * lines, max, min);
  const size = fitSize(longest(at(first)), width, max, min);
  return { size: size, rows: at(size) };
}

/* The largest size in [min,max] at which every label fits `width`. */
function fitSize(labels, width, max, min) {
  const longest = labels.reduce((n, s) => Math.max(n, s.length), 0);
  if (!longest) return max;
  const ideal = width / (longest * CHAR_W);
  return Math.max(min, Math.min(max, Math.floor(ideal * 2) / 2));
}

/* How many characters survive at that size — only bites once fitSize has
   bottomed out on its floor, so most labels are never cut. */
const budget = (width, size) => Math.max(6, Math.floor(width / (size * CHAR_W)));
const clip = (s, n) => (s.length > n ? s.slice(0, n - 1) + "…" : s);

/* ---- drawing ------------------------------------------------------- */

function shell() {
  const w = new ListWidget();
  const g = new LinearGradient();
  g.colors = [BG_TOP, BG_BOTTOM];
  g.locations = [0, 1];
  w.backgroundGradient = g;
  w.setPadding(12, 13, 12, 13);
  return w;
}

function header(w, now, stale) {
  const row = w.addStack();
  row.centerAlignContent();
  const t = row.addText("HK POOLS");
  t.font = Font.semiboldSystemFont(9);
  t.textColor = DIM;
  row.addSpacer();
  const df = new DateFormatter();
  df.dateFormat = "EEE HH:mm";
  const c = row.addText((stale ? "⚠ " : "") + df.string(now));
  c.font = Font.systemFont(9);
  c.textColor = stale ? COLORS.part : DIM;
}

function dot(stack, code) {
  const d = stack.addText("●");
  d.font = Font.systemFont(11);
  d.textColor = COLORS[code] || COLORS.unk;
  return d;
}

function message(w, now, lines) {
  header(w, now, false);
  w.addSpacer(8);
  for (const line of lines) {
    const t = w.addText(line);
    t.font = Font.systemFont(11);
    t.textColor = INK;
    w.addSpacer(3);
  }
  w.addSpacer();
  return w;
}

/* Every layout below sizes its type against the text it is actually going to
   draw, not the text it started with: a detail segment that will be dropped
   for want of room must not shrink the row that outlives it. */

/* One pool: spend the whole tile on it. `big` is the medium tile, where the
   same shape has twice the room and can afford twice the headline. */
function oneWidget(w, row, now, stale, warnings, notes, big) {
  const st = row.st;
  header(w, now, stale);
  w.addSpacer(big ? 8 : 6);

  const name = w.addText(rowLabel(row));
  name.font = Font.semiboldSystemFont(big ? 17 : 13);
  name.textColor = INK;
  name.minimumScaleFactor = 0.7;
  name.lineLimit = 2;

  w.addSpacer(big ? 6 : 4);
  const head = w.addText(HEADLINE[st.code] || "—");
  head.font = Font.boldSystemFont(big ? 30 : 20);
  head.textColor = COLORS[st.code] || COLORS.unk;
  head.minimumScaleFactor = 0.6;
  head.lineLimit = 1;

  // 155pt tile less 13pt padding a side, or 329 for the medium
  const size = big ? 14 : 11.5;
  const lines = stateLines(st, budget(big ? 303 : 129, size), big);

  // the headline sits under the name; the times drop to the foot of the tile,
  // so the slack ends up between them rather than banked below everything
  w.addSpacer(big ? 5 : 3);
  w.addSpacer();
  lines.info.forEach(function (line) {
    const detail = w.addText(line);
    detail.font = Font.systemFont(size);
    detail.textColor = DIM;
    detail.minimumScaleFactor = 0.8;
    detail.lineLimit = 1;
  });

  if (lines.next) {
    w.addSpacer(big ? 4 : 2);
    const next = w.addText(lines.next);
    next.font = Font.systemFont(size);
    next.textColor = st.code === "open" ? COLORS.part : DIM;
    next.minimumScaleFactor = 0.8;
    next.lineLimit = 1;
  }

  footerRow(w, warnings, notes, !big);
}

/* Two or three pools: a stacked row each — name, then its line beneath, so
   the detail gets the full tile width rather than a narrow right-hand column.

   Three on the small tile is the cramped case, and the only one: it keeps the
   detail to a single abbreviated line. Two pools leave a third of the tile
   empty, so they get larger type, a detail free to wrap, and the slack shared
   out between the rows instead of pooled under the last one. */
function stackedRows(w, rows, now, stale, warnings, notes, big) {
  header(w, now, stale);
  w.addSpacer(4);

  // small: a 155pt tile less 13pt padding a side; the dot and gap cost 14 more
  const NAME_W = big ? 288 : 115, DET_W = big ? 289 : 116;
  const cramped = !big && rows.length >= 3;
  const detLines = cramped || big ? 1 : 2;

  const labels = rows.map(rowLabel);
  const nameSize = fitSize(labels, NAME_W, big ? 18 : cramped ? 13 : 15,
                           MIN_NAME);
  const det = fitDetails(rows, !big, DET_W, detLines, nameSize - 2, MIN_DETAIL);
  const nameBudget = budget(NAME_W, nameSize);

  rows.forEach(function (row, i) {
    const head = w.addStack();
    head.centerAlignContent();
    dot(head, row.st.code);
    head.addSpacer(4);
    const name = head.addText(fitLabel(row, nameBudget));
    name.font = Font.mediumSystemFont(nameSize);
    name.textColor = INK;
    name.lineLimit = 1;
    name.minimumScaleFactor = 1;      // sized above; never shrink alone

    det.rows[i].forEach(function (line) {
      const under = w.addStack();
      under.addSpacer(13);             // clear the dot
      const detail = under.addText(line);
      detail.font = Font.systemFont(det.size);
      detail.textColor = DIM;
      detail.lineLimit = 1;
      detail.minimumScaleFactor = 1;
    });

    w.addSpacer(3);                    // a gap the rows always get
    w.addSpacer();                     // and the slack, shared between them
  });

  footerRow(w, warnings, notes, !big);
}

/* Three pools on the medium tile: name and detail share one line, so they are
   fitted against their combined length and share a size — the weight is what
   separates them. */
function mediumWidget(w, rows, now, stale, warnings, notes) {
  header(w, now, stale);
  w.addSpacer(5);

  const ROW_W = 288;
  const labels = rows.map(rowLabel);
  // the row holds a name and a detail, so each is fitted against the pair;
  // as in fitDetails, a second pass re-fits to whatever survived the first
  const combined = (d) => fitSize(labels.map((l, i) => l + d[i]), ROW_W, 14,
                                  MIN_NAME);
  const trim = (size) => rows.map((r, i) =>
    detailFor(r.st, false, Math.max(12, budget(ROW_W, size) - labels[i].length)));
  let details = trim(combined(rows.map((r) => detailLine(r.st, false))));
  const size = combined(details);
  details = trim(size);
  const nameBudget = budget(ROW_W, size);

  rows.forEach(function (r, i) {
    const row = w.addStack();
    row.centerAlignContent();
    dot(row, r.st.code);
    row.addSpacer(5);

    const name = row.addText(fitLabel(r, nameBudget - details[i].length));
    name.font = Font.mediumSystemFont(size);
    name.textColor = INK;
    name.lineLimit = 1;
    name.minimumScaleFactor = 1;

    row.addSpacer();
    const detail = row.addText(details[i]);
    detail.font = Font.systemFont(size);
    detail.textColor = DIM;
    detail.lineLimit = 1;
    detail.minimumScaleFactor = 1;
    detail.rightAlignText();
    w.addSpacer(3);
    w.addSpacer();                     // three rows still leave slack to share
  });

  footerRow(w, warnings, notes, false);
}

/* The last line carries whichever matters more: a weather signal that could
   shut the pools, or — failing that — a name from the Parameter that matched
   nothing, so a silent drop doesn't look like a deliberate omission. */
function footerRow(w, warnings, notes, tight) {
  let text, color;
  if (warnings.length) {
    text = tight ? "⚠ " + warnings[0]
                 : "⚠ " + warnings[0] + " — outdoor pools likely shut";
    color = COLORS.part;
  } else if (notes.guessed.length) {
    text = "⚠ " + notes.guessed.join(", ");
    color = COLORS.part;
  } else if (notes.missing.length) {
    text = "⚠ no match: " + notes.missing.join(", ");
    color = DIM;
  } else return;

  const t = w.addText(text);
  t.font = Font.systemFont(tight ? 9 : 10);
  t.textColor = color;
  t.lineLimit = 1;
  t.minimumScaleFactor = 0.6;
}

/* ---- assembly ------------------------------------------------------ */

async function build() {
  const w = shell();
  const now = hkNow();
  const family = config.widgetFamily || "medium";

  if (!DATA_URL || DATA_URL === "SET_ME")
    return message(w, now, ["Set DATA_URL at the top of the script."]);

  const { data, stale } = await loadData();
  if (!data)
    return message(w, now, ["No data yet — open the script once while online."]);

  const opts = readParam(args.widgetParameter);
  const { picked, missing, guessed } = pickPools(data.pools, opts.pools);
  if (!picked.length)
    return message(w, now, ["No pool matched “" + missing.join(", ") + "”.",
                            "Check the widget Parameter."]);
  const notes = { missing, guessed };

  // small used to be a single pool; it now takes up to three, like medium
  const rows = picked.slice(0, 3).map((x) => ({
    p: x.p, f: x.f,
    st: x.f ? facilityView(x.p, x.f, now) : venueStatus(x.p, now),
  }));

  // only worth a row if a warning is up AND one of these pools is outdoors
  const warnings = rows.some((r) => hasOutdoor(r.p)) ? await loadWarnings() : [];

  // the medium tile always lists them; only the small one has to choose
  // one pool has the roomiest layout, two the next roomiest; only three on
  // the small tile is genuinely cramped, and only it gets the cramped shape
  const alone = rows.length === 1 || (family === "small" && opts.single);
  const big = family !== "small";
  if (alone) oneWidget(w, rows[0], now, stale, warnings, notes, big);
  else if (big && rows.length > 2)
    mediumWidget(w, rows, now, stale, warnings, notes);
  else stackedRows(w, rows, now, stale, warnings, notes, big);

  w.refreshAfterDate = new Date(Date.now() + 15 * 60 * 1000);
  return w;
}

const widget = await build();
if (config.runsInWidget) Script.setWidget(widget);
else if (config.widgetFamily === "small") await widget.presentSmall();
else await widget.presentMedium();
Script.complete();
