// Variables used by Scriptable.
// These must be at the very top of the file. Do not edit.
// icon-color: teal; icon-glyph: swimmer;
// GENERATED by build.py from src/hkpools-widget.js + status.js. Do not edit; your changes will be overwritten.
/* =====================================================================
   HK Pools — iOS home-screen widget (Scriptable)

   Small  : one pool, large.
   Medium : up to three, one line each, plus a weather row when it matters.

   Set DATA_URL below to your published pools.json, then put the pool names
   in the widget's Parameter field, comma-separated. Partial names are fine:
   "kowloon park" finds "Kowloon Park Swimming Pool".

   The status logic lives in status.js and is injected below at build time —
   the web app runs the identical code, so the two can never disagree.
   ===================================================================== */

const DATA_URL = "SET_ME";   // <- your raw.githubusercontent.com pools.json

const WARN_URL =
  "https://data.weather.gov.hk/weatherAPI/opendata/weather.php?dataType=warnsum&lang=en";

const CACHE = "hkpools-data.json";
const WARN_CACHE = "hkpools-warn.json";
const WARN_MAX_AGE_MIN = 30;      // beyond this a cached warning is ignored
const DEFAULT_POOLS = "Kowloon Park, Victoria Park, Morrison Hill";

// dot colours: all open / partly open / closed / group-training-only
const COLORS = {
  open: new Color("#34c759"),
  part: new Color("#ff9f0a"),
  shut: new Color("#ff453a"),
  priv: new Color("#bf5af0"),
  unk:  new Color("#8e8e93"),
};
const INK = new Color("#ffffff");
const DIM = new Color("#ffffff", 0.55);
const BG_TOP = new Color("#12232e");
const BG_BOTTOM = new Color("#0a141b");

/* >>> injected from status.js — edit that file, not this one */
/* =====================================================================
   HK Pools — status engine (canonical)

   The ONE implementation of "is this pool open right now". It is injected
   verbatim into both index.html and hkpools-widget.js at build time, so the
   web app and the iOS widget can never disagree.

   Pure functions only: no DOM, no network, no Scriptable APIs. Takes a pool
   object from pools.json plus a Date, returns status. Node can run it as-is,
   which is how the parity tests work.
   ===================================================================== */

function hkNow(){
  return new Date(new Date().toLocaleString("en-US",{timeZone:"Asia/Hong_Kong"}));
}
function mins(t){ const p=t.split(":"); return (+p[0])*60 + (+p[1]); }
function fmt(t){
  let p=t.split(":"), h=+p[0], m=p[1], ap=h<12?"am":"pm";
  h=h%12||12; return h+":"+m+ap;
}
function isoDay(d){
  return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")
         +"-"+String(d.getDate()).padStart(2,"0");
}
function inMonthRange(rng, mo, day){
  if(!rng) return false;
  var m1=rng[0][0], d1=rng[0][1], m2=rng[1][0], d2=rng[1][1];
  var a=m1*100+d1, b=m2*100+d2, x=mo*100+day;
  return a<=b ? (x>=a && x<=b) : (x>=a || x<=b);
}

/* ---- one facility -------------------------------------------------- */
function facilityStatus(p, f, now){
  var mo=now.getMonth()+1, day=now.getDate(), wd=(now.getDay()+6)%7;
  var nowM=now.getHours()*60+now.getMinutes();
  var today=isoDay(now);
  var out={code:"shut", label:"Closed", note:f.note||"", reason:"", sessions:[]};

  if(!p.public || !f.public){
    out.code="priv"; out.label="Groups only";
    out.note=f.access_note||p.access_note||""; return out;
  }

  for(var i=0;i<p.maintenance.length;i++){
    var m=p.maintenance[i];
    if(inMonthRange(m.range,mo,day) &&
       (m.scope==="venue" || (m.targets && m.targets.indexOf(f.id)>=0))){
      out.label="Maintenance"; out.note=m.label; out.reason=m.label; return out;
    }
  }

  if(f.months && f.months.indexOf(mo)<0){ out.label="Out of season"; return out; }
  if(f.days && f.days.indexOf(wd)<0){ out.label="Not today"; return out; }

  var list, sdays;
  if(f.weekday_sessions && f.weekday_sessions.days.indexOf(wd)>=0){
    list=f.weekday_sessions.sessions; sdays=null;
  } else if(f.sessions){ list=f.sessions; sdays=f.session_days; }
  else { list=p.sessions; sdays=p.session_days; }
  if(!list || !list.length){ out.code="unk"; out.label="Unknown"; return out; }

  var sess=list.map(function(s,i){
    var d = sdays && sdays[String(i)];
    return {from:s[0], to:s[1], skipped: d ? d.indexOf(wd)<0 : false};
  });

  // Weekly cleansing is a venue-wide clock blackout, never a session index:
  // facilities that open from the 2nd session have a different session list.
  if(p.cleansing_weekday===wd){
    var w = p.cleansing_window ||
            (p.sessions && p.sessions.length>1 ? ["10:00", p.sessions[1][1]] : null);
    if(w){
      var split=[];
      sess.forEach(function(s){
        if(s.skipped){ split.push(s); return; }
        if(mins(s.to)<=mins(w[0]) || mins(s.from)>=mins(w[1])){ split.push(s); return; }
        if(mins(s.from)<mins(w[0])) split.push({from:s.from,to:w[0],skipped:false});
        if(mins(s.to)>mins(w[1]))   split.push({from:w[1],to:s.to,skipped:false});
      });
      sess=split; out.cleansing=true;
    }
  }

  var live=sess.filter(function(s){ return !s.skipped; });
  out.sessions=live;

  var closure=(p.closures||[]).filter(function(c){
    if(!c.targets || c.targets.indexOf(f.id)<0) return false;
    var s=c.start.slice(0,10), e=c.end?c.end.slice(0,10):"9999-12-31";
    if(!(s<=today && today<=e)) return false;
    var from = c.start.slice(0,10)===today ? mins(c.start.slice(11)) : 0;
    var to   = (c.end && c.end.slice(0,10)===today) ? mins(c.end.slice(11)) : 1440;
    return nowM>=from && nowM<to;
  })[0];
  if(closure){
    out.label="Closed";
    out.note=closure.reason + (closure.end ? "" : " (until further notice)");
    // `reason` marks a closure we can name; `note` may just be standing text
    // about the facility, which is never why it is shut right now.
    out.reason=out.note;
    return out;
  }

  var cur=live.filter(function(s){ return nowM>=mins(s.from) && nowM<mins(s.to); })[0];
  if(cur){ out.code="open"; out.label="Open"; out.until=cur.to; return out; }
  var next=live.filter(function(s){ return mins(s.from)>nowM; })[0];
  if(next){ out.code="soon"; out.label=fmt(next.from); out.nextRaw=next.from; return out; }
  return out;
}

/* ---- whole venue --------------------------------------------------- */
function venueStatus(p, now){
  var facs=p.facilities.map(function(f){ return {f:f, s:facilityStatus(p,f,now)}; });
  if(!p.public)
    return {code:"priv", label:"Groups only", facs:facs, openN:0, total:0, vague:[]};
  if(!facs.length)
    return {code:"unk", label:"Hours unknown", facs:facs, openN:0, total:0, vague:[]};

  var open=facs.filter(function(x){ return x.s.code==="open"; });
  var openN=open.length;
  var total=facs.filter(function(x){ return x.s.code!=="priv"; }).length;
  var lapOpen=open.some(function(x){ return x.f.lap; });

  // when open, the earliest closing time among open facilities
  var until=null;
  open.forEach(function(x){
    if(x.s.until && (!until || mins(x.s.until)<mins(until))) until=x.s.until;
  });
  // when shut, the earliest next opening
  var nextRaw=null;
  facs.forEach(function(x){
    if(x.s.nextRaw && (!nextRaw || mins(x.s.nextRaw)<mins(nextRaw))) nextRaw=x.s.nextRaw;
  });

  var today=isoDay(now);
  var vague=(p.closures||[]).filter(function(c){
    return !c.targets && c.start.slice(0,10)<=today &&
           (c.end?c.end.slice(0,10):"9999-12-31")>=today;
  });

  var cleansing=facs.some(function(x){ return x.s.cleansing; });

  var code, label;
  if(openN===0){ code="shut"; label = nextRaw ? "Opens "+fmt(nextRaw) : "Closed"; }
  else if(vague.length){ code="part"; label="Open · see notice"; }
  else if(openN===total){ code="open"; label="All open"; }
  else { code="part"; label=openN+" of "+total+" open"; }

  return {code:code, label:label, facs:facs, openN:openN, total:total,
          lapOpen:lapOpen, until:until, nextRaw:nextRaw, vague:vague,
          cleansing:cleansing};
}

/* Node/test export; harmless in a browser or Scriptable. */
if (typeof module !== "undefined" && module.exports)
  module.exports = {hkNow, mins, fmt, isoDay, inMonthRange, facilityStatus, venueStatus};
/* <<< end status.js */

/* ---- data ---------------------------------------------------------- */

const fm = FileManager.local();
const cachePath = (n) => fm.joinPath(fm.cacheDirectory(), n);

function readCache(name) {
  const p = cachePath(name);
  if (!fm.fileExists(p)) return null;
  try {
    return { data: JSON.parse(fm.readString(p)), at: fm.modificationDate(p) };
  } catch (e) {
    return null;
  }
}

function writeCache(name, obj) {
  try {
    fm.writeString(cachePath(name), JSON.stringify(obj));
  } catch (e) { /* a full disk must not take the widget down */ }
}

/* Returns {data, stale}. Falls back to the last good download offline, so a
   widget on the tube still shows correct session times — only closures age. */
async function loadData() {
  try {
    const req = new Request(DATA_URL);
    req.timeoutInterval = 15;
    const data = await req.loadJSON();
    if (!data || !Array.isArray(data.pools) || !data.pools.length)
      throw new Error("pools.json has no pools");
    writeCache(CACHE, data);
    return { data, stale: false };
  } catch (e) {
    const c = readCache(CACHE);
    if (c) return { data: c.data, stale: true };
    return { data: null, stale: true };
  }
}

/* Warnings that shut outdoor pools, per the LCSD rules in pools.json.
   Best-effort: a failed fetch just means no weather row. */
async function loadWarnings() {
  let raw = null;
  try {
    const req = new Request(WARN_URL);
    req.timeoutInterval = 8;
    raw = await req.loadJSON();
    writeCache(WARN_CACHE, raw);
  } catch (e) {
    const c = readCache(WARN_CACHE);
    const ageMin = c ? (Date.now() - c.at.getTime()) / 60000 : Infinity;
    if (!c || ageMin > WARN_MAX_AGE_MIN) return [];
    raw = c.data;
  }
  return relevantWarnings(raw);
}

function relevantWarnings(raw) {
  if (!raw || typeof raw !== "object") return [];
  const out = [];
  for (const key of Object.keys(raw)) {
    const w = raw[key];
    if (!w || w.actionCode === "CANCEL") continue;
    const code = String(w.code || "");
    // thunderstorm, any rainstorm signal, and typhoon signal 3 or above
    if (key === "WTS" || code.startsWith("WRAIN") ||
        (code.startsWith("TC") && !/TC1$/.test(code)))
      out.push(w.type || w.name || key);
  }
  return out;
}

/* ---- matching ------------------------------------------------------ */

/* "victoria park, morrison" -> the pools they name, in the order given.
   Case-insensitive substring, so nobody has to type "Swimming Pool". */
function pickPools(pools, param) {
  const wanted = (param || DEFAULT_POOLS)
    .split(",").map((s) => s.trim().toLowerCase()).filter(Boolean);
  const picked = [];
  const missing = [];
  for (const w of wanted) {
    const hit = pools.find((p) => p.name.toLowerCase().includes(w)) ||
                pools.find((p) => (p.district || "").toLowerCase().includes(w));
    if (hit && !picked.includes(hit)) picked.push(hit);
    else if (!hit) missing.push(w);
  }
  return { picked, missing };
}

const hasOutdoor = (p) =>
  p.type !== "indoor" || (p.facilities || []).some((f) => f.location === "outdoor");

/* ---- phrasing ------------------------------------------------------ */

/* The one-line "when · what" that sits beside each pool name. */
function detailLine(p, st) {
  if (st.code === "priv") return "group training only";
  if (st.code === "unk") return "hours not published";

  const when = st.openN > 0
    ? "until " + fmt(st.until)
    : (st.nextRaw ? "Opens " + fmt(st.nextRaw) : "closed today");

  const why = reason(st);
  return why ? when + " · " + why : when;
}

/* Why it looks the way it does — the half of the line that isn't a clock. */
function reason(st) {
  if (st.openN > 0) {
    if (st.vague && st.vague.length) return "see notice";
    return st.openN === st.total ? "all pools"
                                 : st.openN + " of " + st.total + " pools";
  }
  if (st.cleansing) return "cleansing";

  const shut = st.facs.filter((x) => x.s.code !== "priv");
  if (!shut.length) return "";
  const all = (label) => shut.every((x) => x.s.label === label);
  if (all("Maintenance")) return "annual maintenance";
  if (all("Out of season")) return "out of season";

  // only a stated closure explains the shut — a facility's standing note is
  // not a reason, and outside opening hours nothing needs one
  const named = shut.filter((x) => x.s.reason);
  return named.length === shut.length ? short(named[0].s.reason) : "";
}

const short = (s) => (s.length > 22 ? s.slice(0, 21) + "…" : s);

const HEADLINE = { open: "OPEN", part: "PARTLY OPEN", shut: "CLOSED",
                   priv: "GROUPS ONLY", unk: "NO HOURS" };

/* Strip the boilerplate every LCSD venue name carries. */
const shortName = (n) => n.replace(/\s+Swimming Pool( Complex)?$/i, "");

/* ---- drawing ------------------------------------------------------- */

function shell() {
  const w = new ListWidget();
  const g = new LinearGradient();
  g.colors = [BG_TOP, BG_BOTTOM];
  g.locations = [0, 1];
  w.backgroundGradient = g;
  w.setPadding(12, 13, 12, 13);
  return w;
}

function header(w, now, stale) {
  const row = w.addStack();
  row.centerAlignContent();
  const t = row.addText("HK POOLS");
  t.font = Font.semiboldSystemFont(9);
  t.textColor = DIM;
  row.addSpacer();
  const df = new DateFormatter();
  df.dateFormat = "EEE HH:mm";
  const c = row.addText((stale ? "⚠ " : "") + df.string(now));
  c.font = Font.systemFont(9);
  c.textColor = stale ? COLORS.part : DIM;
}

function dot(stack, code) {
  const d = stack.addText("●");
  d.font = Font.systemFont(11);
  d.textColor = COLORS[code] || COLORS.unk;
  return d;
}

function message(w, now, lines) {
  header(w, now, false);
  w.addSpacer(8);
  for (const line of lines) {
    const t = w.addText(line);
    t.font = Font.systemFont(11);
    t.textColor = INK;
    w.addSpacer(3);
  }
  w.addSpacer();
  return w;
}

function smallWidget(w, p, st, now, stale) {
  header(w, now, stale);
  w.addSpacer(6);

  const name = w.addText(shortName(p.name));
  name.font = Font.semiboldSystemFont(13);
  name.textColor = INK;
  name.minimumScaleFactor = 0.7;
  name.lineLimit = 2;

  w.addSpacer(4);
  const head = w.addText(HEADLINE[st.code] || "—");
  head.font = Font.boldSystemFont(20);
  head.textColor = COLORS[st.code] || COLORS.unk;
  head.minimumScaleFactor = 0.6;
  head.lineLimit = 1;

  w.addSpacer(3);
  const detail = w.addText(detailLine(p, st));
  detail.font = Font.systemFont(10);
  detail.textColor = DIM;
  detail.minimumScaleFactor = 0.7;
  detail.lineLimit = 2;
  w.addSpacer();
}

function mediumWidget(w, rows, now, stale, warnings) {
  header(w, now, stale);
  w.addSpacer(5);

  for (const { p, st } of rows) {
    const row = w.addStack();
    row.centerAlignContent();
    dot(row, st.code);
    row.addSpacer(5);

    const name = row.addText(shortName(p.name));
    name.font = Font.mediumSystemFont(12);
    name.textColor = INK;
    name.lineLimit = 1;
    name.minimumScaleFactor = 0.7;

    row.addSpacer();
    const detail = row.addText(detailLine(p, st));
    detail.font = Font.systemFont(11);
    detail.textColor = DIM;
    detail.lineLimit = 1;
    detail.minimumScaleFactor = 0.7;
    detail.rightAlignText();
    w.addSpacer(5);
  }

  w.addSpacer();
  if (warnings.length) {
    const t = w.addText("⚠ " + warnings[0] + " — outdoor pools likely shut");
    t.font = Font.systemFont(10);
    t.textColor = COLORS.part;
    t.lineLimit = 1;
    t.minimumScaleFactor = 0.7;
  }
}

/* ---- assembly ------------------------------------------------------ */

async function build() {
  const w = shell();
  const now = hkNow();
  const family = config.widgetFamily || "medium";

  if (!DATA_URL || DATA_URL === "SET_ME")
    return message(w, now, ["Set DATA_URL at the top of the script."]);

  const { data, stale } = await loadData();
  if (!data)
    return message(w, now, ["No data yet — open the script once while online."]);

  const { picked, missing } = pickPools(data.pools, args.widgetParameter);
  if (!picked.length)
    return message(w, now, ["No pool matched “" + missing.join(", ") + "”.",
                            "Check the widget Parameter."]);

  const limit = family === "small" ? 1 : 3;
  const rows = picked.slice(0, limit)
    .map((p) => ({ p, st: venueStatus(p, now) }));

  // only worth a row if a warning is up AND one of these pools is outdoors
  const warnings = rows.some(({ p }) => hasOutdoor(p)) ? await loadWarnings() : [];

  if (family === "small") smallWidget(w, rows[0].p, rows[0].st, now, stale);
  else mediumWidget(w, rows, now, stale, warnings);

  w.refreshAfterDate = new Date(Date.now() + 15 * 60 * 1000);
  return w;
}

const widget = await build();
if (config.runsInWidget) Script.setWidget(widget);
else if (config.widgetFamily === "small") await widget.presentSmall();
else await widget.presentMedium();
Script.complete();
